name: Test

on: [push]

jobs:
  test:
    runs-on: macos-26
    strategy:
      matrix:
        include:
          - name: iOS 26.1 on iPhone 17 Pro
            xcode: "26.1.1"
            ios: "26.1"
            device: iPhone 17 Pro
          - name: iPadOS 26.1 on iPad (A16)
            xcode: "26.1.1"
            ios: "26.1"
            device: iPad (A16)
          - name: macOS 26.1
            xcode: "26.1.1"
            ios: "26.1"
            device: My Mac
    name: Test (${{ matrix.name }})
    steps:
    - uses: actions/checkout@v6
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_${{ matrix.xcode }}.app && /usr/bin/xcodebuild -version
    - name: Build
      run: xcodebuild build -scheme ReadEvalPrintLoop -project ReadEvalPrintLoop.xcodeproj -destination 'platform=iOS Simulator,name=${{ matrix.device }},OS=${{ matrix.ios }}' | xcpretty && exit ${PIPESTATUS[0]}
    - name: Run tests
      run: xcodebuild test -scheme ReadEvalPrintLoop -project ReadEvalPrintLoop.xcodeproj -destination 'platform=iOS Simulator,name=${{ matrix.device }},OS=${{ matrix.ios }}' | xcpretty && exit ${PIPESTATUS[0]}
