name: Test

on: [push]

jobs:
  test:
    runs-on: macos-26
    strategy:
      matrix:
        include:
          - name: iOS 26.1 on iPhone 17 Pro
            xcode: "26.1.1"
            ios: "26.1"
            device: iPhone 17 Pro
          - name: iOS 18.6 on iPhone 16 Pro
            xcode: "26.1.1"
            ios: "18.6"
            device: iPhone 16 Pro
    name: Test (${{ matrix.name }})
    steps:
    - uses: actions/checkout@v6
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_${{ matrix.xcode }}.app && /usr/bin/xcodebuild -version
    - name: Run tests
      run: xcodebuild test -scheme ReadEvalPrintLoop -project ReadEvalPrintLoop.xcodeproj -destination 'platform=iOS Simulator,name=${{ matrix.device }},OS=${{ matrix.ios }}' | xcpretty && exit ${PIPESTATUS[0]}
